name: Angular Example CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  angular-example-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '22.20.0'

    - name: Install dependencies
      run: npm ci
      working-directory: examples/angular-example

    - name: Build Angular application
      run: npm run build
      working-directory: examples/angular-example
      env:
        CI: true