name: Push docs to knowledgebase
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main
jobs:
  Copy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: docknetwork/knowledgebase-docs
          token: ${{ secrets.KNOWLEDGEBASE_PR_TOKEN }}
          path: knowledge-base

      - name: Copy files
        run: |
          # Specify the files or directories you want to copy
          cp -r docs/* knowledge-base/developer-documentation/wallet-sdk

      - name: Get branch name
        id: get_branch
        run: echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Create a new branch
        run: |
          cd knowledge-base
          git checkout -b $branch_name

      - name: Commit changes
        run: |
          cd knowledge-base
          git config user.name "${{ github.triggering_actor }}"
          git config user.email "mike@dock.io"
          # Get the commit message from the merged PR
          commit_message="${{ github.event.pull_request.title }}"
          git add -A .
          git status
          git commit -m "Copy files from ${{ github.event.pull_request.head.repo.full_name }} branch $branch_name: $commit_message"
          # Create PR
          gh auth login --with-token ${{ secrets.KNOWLEDGEBASE_PR_TOKEN }}
          git push -u origin ${{ env.branch_name }}
          gh pr create \
            --body "This PR copies /docs files from ${{ github.event.pull_request.head.repo.full_name }}." \
            --title "${{ github.event.pull_request.title }}" \
            --head "${{ env.branch_name }}" \
            --base "main"
