name: Lint and test
on: push

# Auto cancels previous running jobs on each new commit
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lintAndTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          TESTING_API_URL: ${{secrets.TESTING_API_URL}}
        run: | 
          export NODE_OPTIONS="--max_old_space_size=12096"
          export CI=true
          npm run test:ci
