name: NodeJS Example CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  nodejs-example-install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.2.0'

    - name: Install dependencies
      run: npm ci
      working-directory: examples/nodejs-example
      env:
        CI: true